services:
  client:
    build:
      context: ./client
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://backend:8081
    ports:
      - "3000:3000"
    depends_on:
      - backend
    
  backend:
    build:
      context: ./backend  
    ports:
      - "8081:8081"
    healthcheck:
      test: ["CMD-SHELL", "python -c 'import urllib.request; urllib.request.urlopen(\"http://localhost:8081\")' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
